- Languages/C++/Hello World !
Just printed Hello World for demo.
> Created Hello World program

- Languages/Java/Sorting.java
> sorting in java

- Languages/Javascript/js-hello-world.js
Simple ( but not so simple ) hello world code.
> My first commit to Open Source

- Languages/Java/Sorting.java
> Merge Sort implementation in Sorting.java

- Languages/C++/ExtendedEucleidian.cpp
This is a program for extended euclidean algorithm.
> Euclidean Algorithm

- Languages/C++/Nqueens.cpp
gives position of each queen in max 10x10 matrix.
> added Nqueens for max 10x10 arr

- Languages/C++/IntersectionOfarrays.cpp
This code gives intersection of 2 arrays using STL hashing.
> Intersection of 2 arrays

- Languages/C++/verticalorderBTprint.cpp
Vertical order Binary print with Hashing .
> Binary tree vertical order print

- Languages/C++/Largest_Sum_Contiguous_Subarray.cpp
Added function that calculates maximum subarray sum using minimum sum and without following the DP paradigm of the normal Kadane algorithm
> Largest_Sum_Continguous_Subarray_upd.cpp

- Languages/C++/Sieve of Eratosthenes
Included cstring header file which includes memset as without it the code would not compile
> Seive_of_Eratosthenes.cpp

- Languages/C++/fastExponentiation.cpp
to calculate x to the power y fast in log(y)
> Fast exponentiation code in c++

- Languages/C++/rat_in_a_maze_problem.cpp
Solved Rat in a Maze using Recursion and Backtracking technique.
> Added Rat in a Maze Problem

- Languages/C++/Euler_phi
Program to calculate Euler Totient Function
> Euler_phi.cpp

- Circular_Linked_List.c
This program inserts deletes and traverses a circular linked list
> Added Circular_linked_List.c

- find_unique.cpp
This program finds a unique number amongst other even times repeating numbers. It use XOR operator.
> Add find_unique.cpp

- Languages/C++/Number_of_divisors.cpp
> Number of Divisors

- Languages/C++/Number_of_divisors.cpp
> Number_of_Divisors.cpp

- Languages/Java/Stack.java
This is an implementation of stack traversal, push and pop using references
> Added Stack.java

- Languages/Java/LexoPermute.java
permutations in lexographical order of entered string
> Added permutations in Lexographical order

- Languages/HelloWorldInTS.ts
> TypeScript rocks!

- Languages/Java/Reverse.java
> Added reversing a number

- Languages/Java/DiamondPattern.java
Added Diamond Pattern for n rows
> Diamond Pattern added

- Languages/C++/Reach_the_final_destination(StairCase Question)
A person is at 0 level he has to reach a certain floor which is given by the user. We need to use recursion to solve the problem. In this no memoization is used.
> Create Reach_the_final_destination(StairCase Question)

- Languages/C++/binarysearchrecursive.cpp
- neuralnetworkmodel.m
Addition  of Neural Network model and binary search recursive algorithm
> Contribution by Swapnil Tiwari

- numgen.cpp
> Added new file

- Languages/Java/QuickSort.java
Add extras validations in QuickSort Java
> Add extras validations in QuickSort Java

- Languages/Java/linear_search.java
- Languages/Java/stack_using_array.java
Fix package and class name errors in stack_using_array and linear_searching classes.
> Fix package and class name errors

- Languages/Java/ArrayInverse.java
- Languages/Java/BST/BinarySearchTree.java
- Languages/Java/BST/Main.java
- Languages/Java/BST/PrintKDistance.java
- Languages/Java/CollectMaxCoins.java
- Languages/Java/DiamondPattern.java
- Languages/Java/GCD.java
- Languages/Java/Kadaans_Algorithm.java
- Languages/Java/LengthOfLIS.java
- Languages/Java/LexoPermute.java
- Languages/Java/LinkedList/DLL.java
- Languages/Java/LinkedList/LL.java
- Languages/Java/LinkedList/LinkedList.java
- Languages/Java/LinkedList/LinkedListMain.java
- Languages/Java/Reverse.java
- Languages/Java/Sorting.java
- Languages/Java/dynamic_method_dispatch.java
Removed errors from package names, imports and empty lines.
> Removed errors from package names, imports and empty lines.

- README.md
> hacktober19

- arraysum.java
- swapping of two numbers
Trying git commands and updating current program
> updating a program

- linkedlist.c
Added a new c program on the concept of linked list
> added a new c program

- Languages/C++/Edit_distance_Leetcode_hard_level.cpp
Leetcode Hard Problem : link : https://leetcode.com/problems/edit-distance/
2D DP solution
> added leetcode(hard) edit distance 2D DP problem

- Languages/Java/multithreadedSorting.java
A project for an application which uses java multithreading to show the performance of various sorting algorithms simultaneously.
_ Still Work In Progress
> A separate sorting file

- Languages/C++/Longest_increasing_subsequence_O(nlogn).cpp
Leetcode Problem Link : https://leetcode.com/problems/longest-increasing-subsequence/
Question says to find longest increasing subsequence in O(nlogn) instead of O(n^2).
> Longest increasing subsequence O(nlogn)

- Languages/C++/Insertion_in_binary_trees
- Languages/C++/monty_hall_paradox.cpp
A basic monty hall paradox program.
> Added Monty Hall Paradox

- Languages/Python/loadingSoundFile.py
Processing SoundFile In Python
> Creating soundFile.py

- .idea/.gitignore
- .idea/Hacktoberfest1.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- Languages/Java/MaxHeap.java
Adds MaxHeap class and its various methods to Java Packet in Master
> Add MaxHeap Class to Java Packet

- Languages/Kotlin/IsPrime.kt
Kotlin program to check if a number is prime
> kotlin is prime

- Languages/C++/bubble_sort.cpp
> Palindrome

- Languages/Python/calculator.py
> Basic calculator

- Languages/C++/factors_of_numbers.cpp
factors_of_numbers.cpp (a c++ program ) added
> factors_of_numbers

- Languages/C++/mergeTwoSortedLL.cpp
@shivaylamba - Can you please review?
> Add merge two sorted linked list.cpp

- Languages/C++/Burst Balloon DP.cpp
@shivaylamba - Can you please review?
> Add Burst Balloon DP.cpp

- Languages/Java/NextSmallerWithSameDigits.java
Added new algorithm to Java language section for Hacktoberfest.
Algorithm description:
Kata "Next smaller number with the same digits" solution
[Check on Codewars](https://www.codewars.com/kata/next-smaller-number-with-the-same-digits/java)
> New Java algorithm

- Languages/C++/detect loop.cpp
- shortest distance bw two node.cpp
@shivaylamba - Can you please review?
> Add detect loop in linked list.cpp

- Languages/C++/BFS.cpp
- Languages/C++/DFS.cpp
@shivaylamba - Can you please review?
> Add graph traversal algos(BFS & DFS)

- Languages/Java/Palindrome.java
Made use of `StringBuilder.reverse()`
> Add java one liner solution for palindrome problem

- Languages/Java/DecompressZip.java
> Added decompress zip method

- Languages/C++/StackReverse(By Recursion).cpp
This algo reverses a stack using recursion.
> Addede StackReversion(Using Recursion).cpp

- Languages/Kotlin/SelectionSort.kt
Example of selection sort with Kotlin.
> Add selection sort

- Languages/C++/MinPriorityQueueImplementation.cpp
Added the cpp implementation of a MinPriorityQueue with the assumption that the element's value is same as its priority and vice-versa.
> MinPriorityQueue Implementation

- Languages/Java/GCD using recursion.java
Added program to calculate GCD using recursion.
> Create GCD using recursion.java

- Languages/Java/Tower Of Hanoi.java
Using a helper stick (peg), shift all rings from peg A to peg B using peg C.
All rings are initially placed in ascending order, smallest being on top.
No bigger ring can be placed over a smaller ring.
> Create Tower Of Hanoi.java

- Languages/Python/L-layer shallow neural network.py
added vectorised implementation of L-layers shallow neural networks code for predicting the output of the mnist handwritten digits.
> added code for shallow L-layered neural networks

- Languages/C/InsertionSort.c
Added Insertion Sort in C language.
> Added Insertion Sort

- Languages/C++/DiamondPattern
> DiamondPattern

- Languages/C++/stack.cpp
Push, Pop, Peek, IsEmpty functions added in stack implementation using C++.
> Added stack.cpp in C++ folder. It is the implementation of stack DS in C++

- Languages/C++/BST.cpp
- Languages/C++/Dijkstra.cpp
> adding Dijkstra Algo + BST

- Languages/C/int_to_binary_string.c
Under the C section, I added a little program to convert integer numbers into binary
> C program to convert integer numbers into binary

- Languages/C++/india.cpp
this on compile and running creates the india map
> [ADD] india map

- Languages/C++/TowerOfHanoi.cpp
Tower of Hanoi using recursive approach
> Tower of Hanoi

- Languages/C/avl_tree.c
> Added AVL Tree DS

- Languages/C++/Hello_India.cpp
> fast; wasn't required!

- Languages/C++/bubblesort.cpp
> bubblesort added

- Languages/C++/duplicate_remove.cpp
Remove duplicates from a string using STL in C++
> duplicate_remove.cpp

- Languages/C++/find_rep.cpp
CPP program to find and replace the value
> find_rep.cpp added

- README.md
Removed: No. 15
Left: No. 9
Updated: All list numbers after 16
> Remove dulpicate 'Killed by Google' entry from the README.md file.

- Languages/Java/LinkedList/CircularLinkedList.java
- merge sort trial.cpp
merge sort using arrays in cpp
> merge sort 

- Languages/Java/LongestBitonicSubsequence.java
LBS
Created Longest Bitonic Subsequence
> Created Longest Bitonic Subsequence

- Languages/C++/swp.cpp
The first element is paired with a second, third element is paired with fourth and so on. Then the position of the elements of each pair. Remember the first and last pair always remain unchanged.
> Swapping pairs

- Languages/C++/tribonacci.cpp
Hypothetical Tribonacci series which is analogous to the Fibonacci series.
> Tribonacci series

- Languages/Python/intersectionOf3SortedArrays.py
- Languages/Python/steppingNumbers.py
- Languages/Python/twoSumBsts.py
- Languages/Python/validPalindrome.py
Contest Link
[https://leetcode.com/contest/biweekly-contest-10](url)
> Problem Links and Solutions Leetcode Biweekly Contest 10

- helloWorld.rs
> Rust Beginning

- hello.ml
- shamirSharing.py
> Hello world by OCaml

- Languages/Python/openCvCam.py
python program for image conversion RGB to Gray
> python program for image conversion RGB to Gray

- Languages/C++/QC.cpp
Input is a number having very large number of digits. This program outputs the maximum number of groups number can be divided into such that sum of digits is divisible by 3.
> Codeforces_Contest1005

- Languages/C++/Caeser_Cipher.cpp
Takes original string and a ciphered text to extract the key and then decode the input string.
> Caeser_Cipher

- Languages/C++/QA.cpp
Input is start time and end time of a contest. Output is the mid time of the contest.
> Codeforces_Contest1133

- Languages/C/Fibonacci Series Recursion.c
- Languages/C/Fibonacci Series.c
- Languages/C/Fibonacci Triangle.c
- Languages/C/Matrix Mutiplication.c
- Languages/C/Number Triangle.c
Eg Output:
Enter the limit:5
1
1	1	
1	1	2	
1	1	2	3	
1	1	2	3	5
> Fibonacci Triangle

- Languages/C/Fibonacci Series Recursion.c
- Languages/C/Fibonacci Series.c
- Languages/C/Matrix Mutiplication.c
Output:
enter the number of row=3
enter the number of column=3
enter the first matrix element=
1 1 1
2 2 2
3 3 3
enter the second matrix element=
1 1 1
2 2 2
3 3 3
multiply of the matrix=
6 6 6
12 12 12
18 18 18
> Matrix Multiplication

- Languages/C/Fibonacci Series Recursion.c
- Languages/C/Fibonacci Series.c
- Languages/C/Matrix Mutiplication.c
- Languages/C/Number Triangle.c
Eg Output:
enter the range= 4
1
121
12321
1234321
> C Program to print Number Triangle

- Languages/C/Fibonacci Series Recursion.c
- Languages/C/Fibonacci Series.c
Let's see the Fibonacci series program in c without recursion.
Output:
Enter the number of elements:15
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377
> Fibonacci Series in C without recursion

- Languages/C/Fibonacci Series Recursion.c
- Languages/C/Fibonacci Series.c
Output:
Enter the number of elements:15
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377
> Fibonacci Series using recursion in C

- Languages/C/DeletionArray.c
Deleting an element in an array
> Added Deletetion in an array

- Languages/Python/hello.py
one more and i can get that free tshirt!
> made a hello world with python 2.7

- Languages/C/RevLinkedList
Added program to reverse a linked list
> Added RevLinkedList

- Languages/C/Queueprograms.c
> Added QueuePrograms

- Languages/C++/zoom_bilinear.cpp
Zooming image using bi-linear interpolation.
> Added a code for image zooming

- 25780367.java
CodeChef  August Long Challenge 2019
> Zombies and the Caves

- Languages/HTML/Forif.html
- Languages/HTML/onChance.html
> Updated Forif.html and onChance

- Languages/C/binary-search.c
- Languages/C/selection-sort.c
added a new file, selection-sort.c containing program of selection sort in c.
>  selection-sort.c 

- helloworld.cpp
> add helloworld.cpp

- Languages/C/fibonacciNumber.c
> Created fibonacciNumber.c

- Languages/Python/check_prime.py
add snippet code for check prime in python language
> add check_prime to Python language

- Languages/C/Swap two numbers without using third variable .c
Added C Code for swapping two numbers without using additional space
> C Code for Swapping two numbers without using new variable

- Languages/Python/Geometric_Sum.py
- Languages/Python/lan_search.py
- Languages/Python/profanity_checker.py
Added Python programs for lan search, profanity checker and geometric sum.
> Added Python Programs

- Languages/C++/vertical_flip_video.cpp
Video flip algorithm using webcam
> Added code for video flip

- Languages/Python/memoryGameGUI/game.py
this is a memory game whis is developed in Tkinter Python GUI frame work
> memory game which is developed in python tkinter

- Languages/Python/simple_network_scanner.py
This is basic network scanner that can scan the all devices which are in the connected network and give their ip address and mac address. Follow the isntructions clone the repository and go into the reposistory folder. install python dependencies using requirements,txt with the follwing command.
pip3 install -r requirements.txt
sudo python3 network_scanner.py -t [IP address range]
in the IP address range variable, you want to put your range in the CIDR notation(192.168.1.1/24)
Traceback (most recent call last): File "network_scanner.py", line 1, in import scapy.all as scapy ModuleNotFoundError: No module named 'scapy' If you had this problem download scapy from this command sudo apt-get install python-scapy
> I have added a network scanner in python

- Languages/Python/mac_changer.py
We can't change the mac permanently but we can change the mac address temporarily. It will use to impersonate or hide your mac address
> Mac address changer

- graph/AbstractGraph.hpp
- graph/AdjacencyList.hpp
- graph/AdjacencyMatrix.hpp
- graph/DirectedGraph.hpp
- graph/GraphAdjacencyBase.hpp
- graph/UndirectedGraph.hpp
Graph classes
used Inheritance 
Implementation of Graph algorithms such as BFS,DFS
>  Graph Classes

- README.md
> Hacktoberfest 2019

- Languages/Java/Dynamic Programming/Fibonacci.java
This is an algorithm to implement the Fibonacci Nth element problem
> Fibonacci is added

- Languages/C++/longest_palindromic_subsequence.cpp
Program for Longest Palindromic subsequence in c++.
> Add longest Palindromic subsequence

- saddlepoint.cpp
It finds out saddle point in a matrix
> Added saddlepoint.cpp

- tic tac toe program.cpp
a tic tac toe program created with c language
> add tic tac toe program.cpp

- Languages/C++/HelloWorld.cpp
> Added Hello World Program

- Languages/HTML/hello.html
I added a page in Html hello world
> Hacktoberfest hello.html for HTML

- Languages/HTML/SimpleForm.html
> Added Simple HTML Form

- Languages/C++/ReverseLinkedList.cpp
Added Reverse Linked List Program
> Added Reverse Linked List Program

- Languages/C++/Tower-Of-Hanoi.cpp
> Added Tower Of Hanoi Program

- Languages/C/Move.c
Coloured ncurses example where you just move around and collect points
> NCurses Example

- Languages/Java/NextGreaterElement.java
Next Greater Element Program in O(n) using stack
> Next Greater Element Program

- vector.cpp
A basic program to display the "Getter" and "Setter" functions while working with Vectors.
> Vector.cpp

- SelectionSort.cpp
A very basic Selection Sort for sorting elements into Ascending Order.
> Basic Selection Sort

- findUsingRecursion.cpp
Finding an Element with Minimum and Maximum Elements using Recursive approach.
> Finding an Element

- FactorialUsingRecursion
Shows 2 classical approaches of finding factorial via Recursion, with varying time complexities.
> Factorial Using Recursion

- Languages/Javascript/tic-tac-toe/app.js
- Languages/Javascript/tic-tac-toe/index.html
- Languages/Javascript/tic-tac-toe/style.css
Hello!
I added a very simple tic-tac-toe program based on the DOM. I'm not a very experienced programmer, so there's probably a lot of room for improvement.
Thank you for maintaining this repository!
> A simple tic-tac-toe program in Javascript

- Languages/Javascript/Random Background Color Generator/index.html
- Languages/Javascript/Random Background Color Generator/script.js
random background color generator web application
> random background color generator

- Languages/HTML/CircleRipple.html
- Languages/HTML/HTML-Editor.html
- Languages/Javascript/JSPromises.js
- Languages/Javascript/TextFileDownload.js
contains code for Promises in JS
> Add Code for Promises in JS

- Languages/HTML/CircleRipple.html
- Languages/HTML/HTML-Editor.html
- Languages/Javascript/TextFileDownload.js
This File contains JS code for downloading dynamically text files 
Make a call to these functions accordingly
> Add Code TextFileDownload.js 

- Languages/Kotlin/is_armstrong.kt
Added Kotlin program to find whether a number is Armstrong or not
> Added Kotlin program to find whether a number is Armstrong or not

- Languages/Perl/capitalize.pl
I wrote a short perl script that capitalizes the string that was provided on input.
> Added perl script to capitalize strings

- Languages/Kotlin/linear_search.kt
Added linear search program in Kotlin
> Added linear search program in Kotlin

- Languages/C++/wine_problem.cpp
//C++
Merge, the problem doesn't exist already.
> Wine problem

- Languages/Python/flip.py
- Languages/Python/rotate.py
Pass an image to command line argument and rotate it in three different angle
> Rotate a given image

- Languages/Swift/hello_world.swift
Added folder for adding programs in Swift language and added hello world program in Swift.
> Added folder for Swift language and added hello world program in Swift.

- Languages/HTML/CircleRipple.html
- Languages/HTML/Editor-HTML.html
- Languages/HTML/HTML-Editor.html
- Languages/Javascript/TextFileDownload.js
File contains Html code for Html editor, with syntax highlighting & auto completion 
Ready to use file
> Add code for Html-Editor

- Languages/Python/armstrong_number.py
A Python program to check if the number provided by the user is an Armstrong number or not.
> Added a python script to check Armstrong number

- Languages/HTML/CircleRipple.html
- Languages/HTML/CircularRipple.html
- Languages/Javascript/TextFileDownload.js
This File contains HTML code for Circular Ripples
Download  file and its ready to use
> Add HTML code for Circular Ripple

- out/production/Hacktoberfest1/C#/Maquina de Casino/Form1.cs
- out/production/Hacktoberfest1/C#/Maquina de Casino/README.md
- out/production/Hacktoberfest1/C#/NReinas/Form.cs
- out/production/Hacktoberfest1/C#/NReinas/README.md
En este caso y por cuestiones prácticas el problema se trabajó con 5 reinas.
> Problema de las N Reinas

- Languages/C++/calc_score
the first program i solved on codechef. decided to put it here as my first contribution in github
You are participating in a contest which has 11 problems (numbered 1 through 11). The first eight problems (i.e. problems 1,2,…,8) are scorable, while the last three problems (9, 10 and 11) are non-scorable ― this means that any submissions you make on any of these problems do not affect your total score.
Your total score is the sum of your best scores for all scorable problems. That is, for each scorable problem, you look at the scores of all submissions you made on that problem and take the maximum of these scores (or 0 if you didn't make any submissions on that problem); the total score is the sum of the maximum scores you took.
You know the results of all submissions you made. Calculate …
> calculate score

- XOR_operation.JAVA
> xor_operation code added

- Languages/C++/dijkstra.cpp
- Languages/C++/helloworld.cpp
- matrixKcoins.cpp
A very amazing problem to understand Multidimentional Dynamic Programming
> Added the code for matrix k coins (A 3d Dp Problem)

- the sum and average of multiple user-entered numbers.py
for my contribution to HactoberFest2020
> add python program to find sum and average

- exponentiation_log(n).py
My program implements the algorithm of exponentiation of a number x to the power of n in logarithmic time using Divide & Conquer.
> Added a new python algorithm implementation

- Important interview question on array  Equilibrium index.cpp
> Interview question

- Languages/C++/StringStream_Hackerrank.cpp
- Languages/C++/Vector-Sort_Hackerrank.cpp
I have submitted solutions to 2 questions from hackerrank on c++
> Hackerrank solutions cpp

- Languages/Pascal/hello-world.pas
- multiplication-table.pas
Here is my contribution
Changelog :spiral_notepad: 
* Add new language: [Pascal](https://en.wikipedia.org/wiki/Pascal_(programming_language)) 6eada1e
* Add multiplication-table generator ca08230
> Pascal multiplication table

- snake game.txt
> snake game

- Palindrom.cpp
It'll print all palindrome Between given no.  i.e between 100 to 2000
> Palindrom.cpp

- online_rock_paper_scissors/app.js
- online_rock_paper_scissors/game.html
- online_rock_paper_scissors/style.css
Added a new directory which contains rock paper scissors game which can be played by opening game.html
> Rock paper scissors

- Languages/HTML/DigitalClock.html
I have added code to create a digital clock in HH:MM:SS AM/PM format using html and javascript
> A Digital Clock

- Languages/Python/todo-cmdLine-App.py
I have made a To-Do Command-Line App using Python
> ToDo List In Command-Line

- Languages/Javascript/javascript-practice-programs/0_Multiplication_table.html
- Languages/Javascript/javascript-practice-programs/1_Sum_Of_n_Natural_Numbers.html
- Languages/Javascript/javascript-practice-programs/2_star_pattern_1.html
- Languages/Javascript/javascript-practice-programs/3_star_pattern_2.html
- Languages/Javascript/javascript-practice-programs/4_star_pattern_3.html
- Languages/Javascript/javascript-practice-programs/5_Reverse_A_Number.html
Added programs coded in javascript like
1 .Multiplication table
2. Star patterns
3. Reverse a number or "string"
> Added some Javascript beginners friendly programs

- The Coin change prob solution
Added a dynamic programming hackerrank solution
> The Coin change prob Hackerrank solution

- out/production/Hacktoberfest1/Python/LinkedList.py
> Added linkedlist file

- anagramstrings.cpp
- catalanno.cpp
- permuted_string.cpp
- taylor_series_using_horner's_rul.cpp
- towerofhanoi.cpp
added permuted_string.cpp which explains how you can get all combination of a given set of characters
added tower of hanoi(not really tower of hanoi  because i had  used 4 towers, made sort of mine)
added few more files catalan no, anagramstring ,and  taylor series using horner's rule
> added some new programs that may help some one

- Languages/HTML/blockRace.html
> added blockRace.html

- Languages/Python/power_in_logn.py
A python program with power function to calculate power of any number raised to any( positive, negative or zero) number in time complexity of  O(Logn)
> Added power_in_logn.py

- Languages/C++/Max. substring in string.cpp
- Languages/C++/half-star pattern.cpp
hi,
I've added some Algorithms to the C++ base. I hope you find my work Eligible...
I'm a new contributor so pls don't mind my mistakes.
thank you
> Added Algorithms

- palindrome_check_for_number.java
a simple java program for palindrome check for positive input number.
> Create a java program for palindrome check.

- Languages/C++/Tower_of_hanoi_problem.cpp
This C++ program displays the iterative solution to the Tower of Hanoi problem.
> Tower_of_hanoi_problem.cpp

- arduino/Fuel_Gauge/README.md
- arduino/Fuel_Gauge/iot_arduino_to_android_via_bluetooth_or_wifi.ino
- arduino/Water_Quality_Test/README.md
- arduino/Water_Quality_Test/water_quality_test.ino
Contributing my winning hackathon projects (IoT). I hope it will help other budding developers to have an idea how it is done. I have also included my original repositories in the respective readmes for more clarity.
> hackathon iot projects added

- Languages/C++/ADAMAT.cpp
- Languages/C++/CHFNSWAP.cpp
- Languages/C++/COVID19B.cpp
- Languages/C++/CRDGAME2.py
- Languages/C++/EQDIV.cpp
- Languages/C++/FINXOR.cpp
- Languages/C++/TREE2.cpp
> Solution for Codechef September Long challenge 2020 Division 2

- PasswordGenerator_java/Password.java
- PasswordGenerator_java/pruebaPassword.java
Small exercise made for school
> Added PasswordGenerator in java

- Languages/C++/CircularHeaderLL.cpp
- Languages/C++/PallindromeRecursive.cpp
- Languages/C++/ProcessScheduling.cpp
Added programs for Checking pallindrome string(using recursion), Process scheduling in Queue and menu driven program for circular header linked list.
> Added More Algos

- miller_rabin_prime.cpp
I have added an efficient primality test
> Miller Rabin Primality Test Added

- castle.py
An interactive story mode python game added
> Added a new python game

- AddBinary_num.cpp
Simple Cpp program using Standard Template Library to add 2 binary digit numbers (assume one bit as one number)
> Add_Binary_nos.cpp

- Kadane Algorithm.txt
- Prefix Sum Algorithm.txt
1. Kadane's Algorithm
2. Prefix Sum Algorithm
> Kadane's And Prefix Sum Algorithm

- Linked List/Circluar_Linked__List.c
- Linked List/Concat_LL.c
- Linked List/Count_SumLinked_List.c
- Linked List/Create_LL_using_Insert.c
- Linked List/Create_and_Display_LL.c
- Linked List/Deleteing_LL.c
- Linked List/Deleting_from_LL.c
- Linked List/Doubly_Linked_List.c
- Linked List/Insert_in_LL.c
- Linked List/LinearLinkedList.c
- Linked List/LinkedList_CPP.c
- Linked List/Linked_List.c
- Linked List/Max_LL.c
- Linked List/Merge_LL.c
- Linked List/Polynomial_Linked_List.c
- Linked List/Remove_Duplicate_LL.c
- Linked List/Reverse_LL.c
- Linked List/Search_LL.c
- Linked List/SortedInsert_LL.c
- Linked List/isLoop_LL.c
- Linked List/isSorted_LL.c
Singly ,Doubly and Circular Linked list's all operation
> Linked List

- overloadingNewDelete.cpp
New and Delete operator overloaded
> Added Overloading New and Delete

- check_leap_year.c
> Program to check_leap_year

- tic tac toe program.cpp
It shows percentage, and some dialogues like "Loading packages..." using a simple for loop and system("cls"); , etc. Looks elegant and creative for basic C++ program.
> Added a loading Screen in game.

- GamerNishant_RadixSort.cpp.cpp
adding RadixSort algorithm to master branch.
> adding RadixSort.cpp

- Languages/Kotlin/PalindromeCheck.kt
add palindrome check in kotlin
> add palindrome check in kotlin

- Languages/Javascript/helloworld2.js
[Hackerrank_assignment_4.txt](https://github.com/shivaylamba/Hacktoberfest/files/5325115/Hackerrank_assignment_4.txt)
> Revert 6 patch 2

- HelloHacktoberfest.java
> Added HelloHacktoberfest file

- RockPaperScissorsSpockLizard.py
A simple rock, paper, scissors game in need of some touch ups
> Added a Python game

- pascal.java
"added pascal triangle using java ...please merge it and add the hacktober fest accepted label"
> pascal triangle using java

- Languages/Javascript/hello-world-in-HTML-DOM-via-Javascript
Trying to learn how to use github :)
Thanks for creating this repository allowing us to practice!
Happy Hacktoberfest 2020!
> How to "Hello World" in HTML DOM via JavaScript

- Armstrong Numbers between 1-1000
This program gives the armstrong number between 1 to 1000, having three digits.
> Armstrong Numbers between 1-1000

- Program 23/readme.md
- Program 23/sum_of_square_of_binomial_coefficient.cpp
Added Easiest and simplest algorithm for Sum of Square of Binomial Coefficient
> Added Sum of Square of Binomial Coefficient

- Languages/PHP/logout.php
- Languages/PHP/pdo.php
It's my first PR, I hope I got things right, tried to add a useful piece of php code that can be used as a logout button that anyone can easily use
> added logout.php code for easy php logout redirection

- C++/Memory Game - 1.cpp
- C++/Movie Database - 2.cpp
- C++/Student System - 3.cpp
- C++/Vending Machine - 4.cpp
Add Memory Game, Movie Database, Student System, and Vending Machine
> Add 4 C++ folder with programs

- C/Prim-Algorithm.c
Added Prim's algorithm code for my hacktoberfest contribution
> Prim's Algorithm

- DictionaryAttack.py
> Added Dictionary Attack algorithm in Python

- C++/coin_collector_problem.cpp
Adding a simple solution of coin collector problem in C++ folder.  Problem's description can be found in program's comments.
> Add Coin Collector problem solved in C++

- Selection_sort.c++
This might be the best selection sort algorithm and also my SECOND COMMIT
> added c++ program for selection sort

- Python/ML Algorithms/kNearestNeighbour.py
Added implementation of KNN algorithm from Scratch.
> Added implementation of KNN algorithm

- e^x_series.c
e^x series finds the value of e^x using e^x series expansion.
> Added e^x_series.cpp

- C++/Heapsort.cpp
- C++/SpiralMatrixSort.cpp
Adding a new file that performs sorting on a spiral matrix
Given a matrix, the code converts the given Matrix into sorted spiral matrix
Adding another file to perform heap sort
> Adding files for heap sort and spiral matrix sort

- Print Hello World
> Create Print Hello World

- dfs.cpp
- hello.cpp
> added hello world in c++

- AxBproblem.cpp
- djkstra.cpp
- paperMinimumSplit.cpp
add djkstra.cpp
add paperMinimumSplit.cpp
add AxBproblem.cpp
> add three file of algorithm

- Python/spanish-emoji-fizzbuzz.py
For Hacktoberfest 2020 :) Adding a tweaked solution to Fizzbuzz: my Spanish emoji style Fizzbuzz!
> add spanish-emoji-fizzbuzz

- Bitonic_Sorting.cpp
- lexiographical_sort.cpp
- pigeonSort.cpp
I've added C++ Codes of  Advance Data Structure Sorting as mentioned below:
1: Bitonic_Sort,
2: Lexiographical_Sort, 
3: Pigeon_Sort
> Added Bitonic_Sort , Lexiographical_Sort , Pigeon_Sort

- pearson_correlation.py
- seive.py
Code: Python code to find the pearson correlation
> pearsons correlation

- Python/AES.py
an example of a pycryptodome.
1 basic AES
and 
1 key derived PBKDF2.
> Added AES encryption in Python.

- C++/BinarySearch_Karan.cpp
> BinarySearch_Karan.cpp

- RBM/rbm.py
Hey there
Added a new code for Autoencoders using RBM
Thanks!
> Adding new RBM code

- JavaScript/main.js
javascript code to find largest number in array
> find largest number in an array

- arduino/BT_RGBmix/BT_RGBmix.ino
Added Arduino program to control RGB Night light via smartphone using Bluetooth
> Added new Arduino project

- C++/removeEven.cpp
added removeEven.cpp with problem statement with a brief explanation and my solution.
> added removeEven.cpp

- C/DecimaltoBinary.c
> no need of that line

- Add Two Matrices.cpp
I've added a Programme to add two matrices in c++.
Pls Check and approve it.
> Create Add Two Matrices.cpp

- Languages/C++/ReverseStack.cpp
Added code to reverse a stack using the same stack by recursion.
> Add ReverseStack.cpp

- README.md
> Added Hackoctober logo in README.md file

- C/Matrix Multiplication
c program to multiply two matrices
> matrix multiplication.cpp

- C/pentagon pattern.c
hi this is YogEsh JadhAv studing in engineering 3rd year and want to share this pattern which is complex and i found success in it,ThaNk yOu
> Pentagon Pattern(Hardest on hackerrank)

- declare objects
C++ program to define the concepts of declaring the class, its data members and
member functions. Also write a main () function which declares the objects and uses the
member functions of the class.
> Declare objects

- stepsToSortNumber.cpp
> Added stepsToSortNumber.cpp

- Languages/Python/quadraticequation.py
Above program will solve quadratic equation .
@shivaylamba - Hi shiva , can you please approve my merge request.
> Quadratic equation solver in python

- BinarySearch Implementation
Adding BinarySearch implementation in C folder
> Adding BinarySearch implementation in C folder

- C/Fibonacci.c
Fibonacci series without recursion
> Add Fibonacci.c

- Checking Palindrome.c
C Program to check whether a given string is a palindrome
>  Checking_Palindrome.c

- Languages/C++/SingleSP-Greedy.cpp
Single Shortest Path using Dijkstra's Algorithm by Aaron
Please accept for HacktoberFest 2020
> Created SingleSP-Greedy.cpp

- Linked List/Singly Linked List.cpp
This program has all the basic features of a singly Linked List.
> All Basic functions of Singly LinkedList

- graph/kruskal.cpp
Kruskal's Minimum Spanning Tree Algorithm
> kruskal.cpp

- Languages/Python/max_no_of_stairs.py
A python3 program to calculate the total number of possible stairs systems with the given number ( here 3 ) boxes to make the stairs.
> Adding number of stairs arrangements
